#pragma once
#include "CoreMinimal.h"
#include "E_ANIM_NOTIFY_APPLY_HIT_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_ANIM_NOTIFY_APPLY_HIT_TYPE : uint8 {
    E_APPLY_HIT_DEFAULT,
    E_APPLY_HIT_WITHOUT_NUMERIC,
    E_APPLY_HIT_EFFECT_ONLY,
    E_APPLY_HIT_NUMERIC_ONLY,
    E_APPLY_HIT_MOTION_ONLY,
    E_APPLY_HIT_AVOID_TIMING,
    E_APPLY_HIT_WITHOUT_NUMERIC_AND_SHAKE,
    E_APPLY_HIT_DUMMY,
};

