#pragma once
#include "CoreMinimal.h"
#include "E_ATTRIBUTE_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_ATTRIBUTE_TYPE : uint8 {
    E_ATTRIBUTE_TYPE_PHISICS,
    E_ATTRIBUTE_TYPE_FIRE,
    E_ATTRIBUTE_TYPE_ICE,
    E_ATTRIBUTE_TYPE_THUNDER,
    E_ATTRIBUTE_TYPE_WIND,
    E_ATTRIBUTE_TYPE_LIGHT,
    E_ATTRIBUTE_TYPE_DARK,
    E_ATTRIBUTE_TYPE_ALL,
    E_ATTRIBUTE_TYPE_POISON,
    E_ATTRIBUTE_TYPE_VERTIGO,
    E_ATTRIBUTE_TYPE_CONFUSE,
    E_ATTRIBUTE_TYPE_CHARM,
    E_ATTRIBUTE_TYPE_SLEEP,
    E_ATTRIBUTE_TYPE_CLOSE,
    E_ATTRIBUTE_TYPE_STRAY,
    E_ATTRIBUTE_TYPE_BURN,
    E_ATTRIBUTE_TYPE_FREEZE,
    E_ATTRIBUTE_TYPE_SHOCK,
    E_ATTRIBUTE_TYPE_LACERATION,
    E_ATTRIBUTE_TYPE_STONE,
    E_ATTRIBUTE_TYPE_DAZZLE,
    E_ATTRIBUTE_TYPE_MUD,
    E_ATTRIBUTE_TYPE_DARKNESS,
    E_ATTRIBUTE_TYPE_RECV02,
    E_ATTRIBUTE_TYPE_RECV03,
    E_ATTRIBUTE_TYPE_RECV04,
    E_ATTRIBUTE_TYPE_RECV05,
    E_ATTRIBUTE_TYPE_RECV06,
    E_ATTRIBUTE_TYPE_MAX UMETA(Hidden),
    E_ATTRIBUTE_TYPE_RECOVERLY,
    E_ATTRIBUTE_TYPE_ALL_ATK,
    E_ATTRIBUTE_TYPE_MAGIC,
    E_ATTRIBUTE_TYPE_INVALID,
};

