#pragma once
#include "CoreMinimal.h"
#include "E_BATTLECHARAPANELCTRL_GSTATUS.generated.h"

UENUM(BlueprintType)
enum class E_BATTLECHARAPANELCTRL_GSTATUS : uint8 {
    E_BATTLECHARAPANELCTRL_INIT,
    E_BATTLECHARAPANELCTRL_MOVESRC,
    E_BATTLECHARAPANELCTRL_MOVEDST,
    E_BATTLECHARAPANELCTRL_MOVEPROC,
    E_BATTLECHARAPANELCTRL_MOVEANIMEWAIT,
    E_BATTLECHARAPANELCTRL_MOVEEND,
    E_BATTLECHARAPANELCTRL_SETDIALOG_ERROR,
    E_BATTLECHARAPANELCTRL_WAIT_DIALOG,
    E_BATTLECHARAPANELCTRL_SELECTDIALOG_ON,
    E_BATTLECHARAPANELCTRL_WAIT_CLOSEDIALOG,
    E_BATTLECHARAPANELCTRL_SINIT,
    E_BATTLECHARAPANELCTRL_SMOVESRC,
    E_BATTLECHARAPANELCTRL_SSTATUS,
    E_BATTLECHARAPANELCTRL_SEND,
    E_BATTLECHARAPANELCTRL_CSINIT,
    E_BATTLECHARAPANELCTRL_CSMOVESRC,
    E_BATTLECHARAPANELCTRL_CSSELECT,
    E_BATTLECHARAPANELCTRL_CSEND,
    E_BATTLECHARAPANELCTRL_CSSTATUSDETAILINIT,
    E_BATTLECHARAPANELCTRL_CSSTATUSDETAIL,
    E_BATTLECHARAPANELCTRL_SSTATUSDETAILINIT,
    E_BATTLECHARAPANELCTRL_SSTATUSDETAIL,
    E_BATTLECHARAPANELCTRL_STATUSDETAILINIT,
    E_BATTLECHARAPANELCTRL_STATUSDETAIL,
};

