#pragma once
#include "CoreMinimal.h"
#include "E_BAD_STATUS.generated.h"

UENUM(BlueprintType)
enum class E_BAD_STATUS : uint8 {
    E_BAD_STATUS_NONE,
    E_BAD_STATUS_DEAD,
    E_BAD_STATUS_POISON,
    E_BAD_STATUS_STAN,
    E_BAD_STATUS_CONFUSE,
    E_BAD_STATUS_CHARM,
    E_BAD_STATUS_SLEEP,
    E_BAD_STATUS_CLOSE,
    E_BAD_STATUS_STRAY,
    E_BAD_STATUS_STONE,
    E_BAD_STATUS_DAZZLE,
    E_BAD_STATUS_BURN,
    E_BAD_STATUS_FREEZE,
    E_BAD_STATUS_SHOCK,
    E_BAD_STATUS_LACERATION,
    E_BAD_STATUS_MUD,
    E_BAD_STATUS_DARKNESS,
};

