#pragma once
#include "CoreMinimal.h"
#include "E_BTL_EXTRA_ACTION.generated.h"

UENUM(BlueprintType)
enum class E_BTL_EXTRA_ACTION : uint8 {
    E_BTL_EXTACT_NONE,
    E_BTL_EXTACT_END_VERTIGO,
    E_BTL_EXTACT_END_CONFUSE,
    E_BTL_EXTACT_END_CHARM,
    E_BTL_EXTACT_END_SLEEP,
    E_BTL_EXTACT_END_FREEZE,
    E_BTL_EXTACT_END_SHOCK,
    E_BTL_EXTACT_END_STONE,
    E_BTL_EXTACT_ACT_CONFUSE_00,
    E_BTL_EXTACT_ACT_CONFUSE_01,
    E_BTL_EXTACT_ACT_CHARM_00,
    E_BTL_EXTACT_ACT_CHARM_01,
    E_BTL_EXTACT_ACT_CHARM_02,
    E_BTL_EXTACT_MISS_CLOSE,
    E_BTL_EXTACT_MISS_DAZZLE,
    E_BTL_EXTACT_DAM_LACERATION,
    E_BTL_EXTACT_ACT_MUD,
    E_BTL_EXTACT_ACT_DARKNESS,
    E_BTL_EXTACT_ACT_NOT_ENOUGH_MP,
};

