#pragma once
#include "CoreMinimal.h"
#include "E_BTL_REFLECT_RES_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_BTL_REFLECT_RES_TYPE : uint8 {
    E_BTL_REFLECT_RES_HIT,
    E_BTL_REFLECT_RES_REFLEX,
    E_BTL_REFLECT_RES_ABSORB,
    E_BTL_REFLECT_RES_BLOCK,
    E_BTL_REFLECT_RES_AVOID,
    E_BTL_REFLECT_RES_MISS,
    E_BTL_REFLECT_RES_SUMMON,
    E_BTL_REFLECT_RES_RETURN,
    E_BTL_REFLECT_RES_ANALYZE,
    E_BTL_REFLECT_RES_ESCAPE,
    E_BTL_REFLECT_RES_MAKA,
    E_BTL_REFLECT_RES_ENE_ESC,
    E_BTL_REFLECT_RES_PRESS,
    E_BTL_REFLECT_RES_PRESS_ITEM,
    E_BTL_REFLECT_RES_MAKABEAM,
    E_BTL_REFLECT_RES_NOTACT,
    E_BTL_REFLECT_RES_NOTKOUKA,
    E_BTL_REFLECT_RES_FLAG_MISS,
    E_BTL_REFLECT_RES_BSTBLOCK,
};

