#pragma once
#include "CoreMinimal.h"
#include "E_BTL_SUB_COMMAND_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_BTL_SUB_COMMAND_TYPE : uint8 {
    E_BTL_SUB_COMMAND_TYPE_CHANGE_CHARA,
    E_BTL_SUB_COMMAND_TYPE_AUTO,
    E_BTL_SUB_COMMAND_TYPE_CONDITION,
    E_BTL_SUB_COMMAND_TYPE_ANALYZE,
    E_BTL_SUB_COMMAND_TYPE_BTL_PLAN,
    E_BTL_SUB_COMMAND_TYPE_EXCHANGE,
    E_BTL_SUB_COMMAND_TYPE_ESCAPE,
};

