#pragma once
#include "CoreMinimal.h"
#include "E_BTL_TUTORIAL.generated.h"

UENUM(BlueprintType)
enum class E_BTL_TUTORIAL : uint8 {
    E_DISP_PRESSTURN_BATTLE_WINDOW,
    E_MASK_EXXEPT_SKILL,
    E_DISP_SKILL_WINDOW,
    E_SELECT_ATTACK_ONLY,
    E_DISP_ATTR_WINDOW,
    E_SELECT_SKILL_ONLY,
    E_DISP_PRESSICON_WINDOW,
    E_DISP_MAGATSUHI_SKILL_WINDOW,
    E_DISP_BAD_STATUS_WINDOW,
    E_DISP_GUEST_WINDOW,
    E_DISP_RENZOKU_ENCOUNT_WINDOW,
    E_DISP_MUD_WINDOW,
    E_DISP_DARKNESS_WINDOW,
};

