#pragma once
#include "CoreMinimal.h"
#include "E_BTL_ACT_STAT.generated.h"

UENUM(BlueprintType)
enum class E_BTL_ACT_STAT : uint8 {
    E_BTL_ACT_STAT_EFFLOAD,
    E_BTL_ACT_STAT_NEXTSEQ,
    E_BTL_ACT_STAT_DAZZLE_CHANGE,
    E_BTL_ACT_STAT_CLOSE_EXEC,
    E_BTL_ACT_STAT_COMM_BEFORE,
    E_BTL_ACT_STAT_BADSTATUS,
    E_BTL_ACT_STAT_LOCK,
    E_BTL_ACT_STAT_AUTO,
    E_BTL_ACT_STAT_ATTACKUP,
    E_BTL_ACT_STAT_MISS_BLOCK_ABS,
    E_BTL_ACT_STAT_STOCKSEL,
    E_BTL_ACT_STAT_CANCEL,
    E_BTL_ACT_STAT_WEAK_AUTO,
    E_BTL_ACT_STAT_ESC_SKILL,
    E_BTL_ACT_STAT_CHANGE_ACTOR,
    E_BTL_ACT_STAT_NO_ACT_FINISH,
    E_BTL_ACT_STAT_POISONDEAD,
    E_BTL_ACT_STAT_USED_PRESSITEM,
    E_BTL_ACT_STAT_COUNTER_AFTER,
    E_BTL_ACT_STAT_NAKAMA_WAIT,
    E_BTL_ACT_STAT_NOT_SUMMON,
    E_BTL_ACT_STAT_BUTUATK,
    E_BTL_ACT_STAT_EXCHANGE_HERO,
    E_BTL_ACT_STAT_KAIFUKU,
    E_BTL_ACT_STAT_MAGIC,
    E_BTL_ACT_STAT_ITEM,
    E_BTL_ACT_STAT_SUMMON,
};

