#pragma once
#include "CoreMinimal.h"
#include "E_BTL_STATE_DEBUG_2.generated.h"

UENUM(BlueprintType)
enum class E_BTL_STATE_DEBUG_2 : uint8 {
    E_BTL_STAT_DEBUG_2_D_POA,
    E_CHARM_START,
    E_CHARM_CURE,
    E_CHARM_AID,
    BTL_STAT_DEBUG_2_ENEMYFIRST,
    BTL_STAT_DEBUG_2_PLAYERFIRST,
    E_CHARM_WAIT,
    E_CONFUSE_START,
    E_CONFUSE_FF,
    BTL_STAT_DEBUG_2_ALLMISS,
    E_CONFUSE_WAIT,
    E_NOT_CURE_BST_TIMEOUT,
    E_BSTCALC_LOOP_100,
    E_ITEMDROP_LOOP_100,
    E_BTL_STAT_DEBUG_2_NOPRESS,
    BTL_STAT_DEBUG_2_ALLHANSYA,
    BTL_STAT_DEBUG_2_ALLABS,
    BTL_STAT_DEBUG_2_ALLBLOCK,
    BTL_STAT_DEBUG_2_NODAMAGE,
    BTL_STAT_DEBUG_2_ALL_SKILL,
    E_CAN_USE_SURELY_RECOME,
    MERCY_TALK_100,
    E_ALL_USE_SKILL,
    E_NODAMAGE_ONLY_HERO,
    E_NO_UPLIFTING_GAUGE,
    E_COUNTER100,
    E_AUTO_LOG_ON,
    E_FORCE_RENZOKU_ENCOUNT,
    E_NOT_FORCE_RENZOKU_ENCOUNT,
    E_FORCE_CHALLENGE_MODE,
    E_AI_LOG,
};

