#pragma once
#include "CoreMinimal.h"
#include "E_BTN_HELP_MAPPING_KEY_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_BTN_HELP_MAPPING_KEY_TYPE : uint8 {
    None,
    Utl_Action,
    Utl_Cancel,
    Utl_Up,
    Utl_Down,
    Utl_Left,
    Utl_Right,
    Utl_UpDown,
    Utl_FaceTop,
    Utl_FaceLeft,
    Utl_ShoulderLeft,
    Utl_ShoulderRight,
    Utl_TriggerLeft,
    Utl_TriggerRight,
    Utl_SpecialLeft,
    Utl_SpecialRight,
    Utl_RStickUp,
    Utl_RStickDown,
    Utl_RStickUpDown,
    Utl_StickButtonRight,
    Utl_MouseAction,
    Utl_MouseCancel,
    Utl_MovieSkip,
    KeyConfig_Delete,
    Map_Action,
    Map_Attack,
    Map_CampOpen,
    Map_ActionJump,
    Map_CameraReset,
    Map_Traport,
    Map_AutoHeal,
    Map_Dash,
    Map_Dash_R,
    Map_AutoMap,
    Map_ViewDown,
    Map_ToggleAutoRun,
    Map_Estoma,
    Map_Save,
    MoveForward,
    MoveRight,
    MoveForwardRight,
    LookUp,
    LookRight,
    LookUpRight,
    Automap_ScrollUp,
    Automap_ScrollRight,
    Automap_ScrollUpRight,
    GardenMoveUp,
    GardenMoveRight,
    AutoMapZoom,
};

