#pragma once
#include "CoreMinimal.h"
#include "E_BTL_UPLIFTING_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_BTL_UPLIFTING_TYPE : uint8 {
    E_BTL_UPLIFTING_TYPE_RANDVALUE,
    E_BTL_UPLIFTING_TYPE_WEAK,
    E_BTL_UPLIFTING_TYPE_COMBO,
    E_BTL_UPLIFTING_TYPE_CRITICAL,
    E_BTL_UPLIFTING_TYPE_MISS,
    E_BTL_UPLIFTING_TYPE_BLOCK,
    E_BTL_UPLIFTING_TYPE_ABSORB,
    E_BTL_UPLIFTING_TYPE_REFLEX,
    E_BTL_UPLIFTING_TYPE_MAPATTACK,
    E_BTL_UPLIFTING_TYPE_TAISEI,
    E_BTL_UPLIFTING_TYPE_DEFENSE,
    E_BTL_UPLIFTING_TYPE_TURNEND,
    E_BTL_UPLIFTING_TYPE_BTLSTART,
    E_BTL_UPLIFTING_TYPE_SELECT_DEFENSE,
};

