#pragma once
#include "CoreMinimal.h"
#include "E_BTL_BOSS_FLAG.generated.h"

UENUM(BlueprintType)
enum class E_BTL_BOSS_FLAG : uint8 {
    E_INVALID,
    E_BOSS,
    E_NOT_ORDER,
    E_DEAD_WITH_BOSS,
    E_TARGET_SELECT_WHEN_ALONE,
    E_TARGET_SELECT_BLOCK_BOSS,
    E_TAKE_AWAY_ALL_CHAGE,
    E_TAKEN_CHAGE,
    E_TARGET_SELECT_ELECTRIFICATION,
    E_BLOCK_ELECTRIFICATION,
    E_IMMORTALITY,
    E_DOWN,
    E_BOSS_DOWN_UNTIL_NOT_ORDER,
    E_BOSS_DOWN_UNTIL_NOT_SELECT,
    E_ABSOLUTE_BLOCK,
    E_CHANGE_TAISEI,
    E_BOSS_FIRE_WEAK,
    E_BOSS_ICE_WEAK,
    E_HP_HALF,
    E_BOSS_ALL_WEAK,
    E_DEAD_WITH_MODECHANGE,
    E_SHARE_OPEN_AISHOU,
    E_SHARE_HP_RATE,
    E_TURNEND_RETURN,
    E_DEAD_HP0,
    E_NO_NEAR_DEATH_MOTION,
    E_NOT_SELECT,
    E_NOT_ADD_PRESS,
    E_TURNSTART_RETURN,
    E_DEAD_WHITE_OUT,
    E_PROVKE_NOT_SELECT,
};

