#pragma once
#include "CoreMinimal.h"
#include "E_BTL_COMMAND_ACT.generated.h"

UENUM(BlueprintType)
enum class E_BTL_COMMAND_ACT : uint8 {
    E_BTL_COMMAND_ACT_SKILL_0,
    E_BTL_COMMAND_ACT_SKILL_1,
    E_BTL_COMMAND_ACT_SKILL_2,
    E_BTL_COMMAND_ACT_SKILL_3,
    E_BTL_COMMAND_ACT_SKILL_4,
    E_BTL_COMMAND_ACT_SKILL_5,
    E_BTL_COMMAND_ACT_SKILL_6,
    E_BTL_COMMAND_ACT_SKILL_7,
    E_BTL_COMMAND_ACT_ATTACK,
    E_BTL_COMMAND_ACT_DEFENSE,
    E_BTL_COMMAND_ACT_TALK,
    E_BTL_COMMAND_ACT_ITEM,
    E_BTL_COMMAND_ACT_SUMMON,
    E_BTL_COMMAND_ACT_BUF0,
    E_BTL_COMMAND_ACT_BUF1,
    E_BTL_COMMAND_ACT_BUF2,
};

