#pragma once
#include "CoreMinimal.h"
#include "E_BTL_UI_COMM_STEP.generated.h"

UENUM(BlueprintType)
enum class E_BTL_UI_COMM_STEP : uint8 {
    E_BTL_UI_COMM_STEP_NONE,
    E_BTL_UI_COMM_STEP_COMM_MENE,
    E_BTL_UI_COMM_STEP_SKILL_MENU,
    E_BTL_UI_COMM_STEP_ITEM_MENU,
    E_BTL_UI_COMM_STEP_TALK,
    E_BTL_UI_COMM_STEP_ESCAPE_MENU,
    E_BTL_UI_COMM_STEP_ACT_END_MENU,
    E_BTL_UI_COMM_STEP_CONDITION,
    E_BTL_UI_COMM_STEP_ANALAYZE,
    E_BTL_UI_COMM_STEP_PLAN,
    E_BTL_UI_COMM_STEP_TARGET_SELECT,
    E_BTL_UI_COMM_STEP_ASYNC_WAIT,
    E_BTL_UI_COMM_STEP_IDLING,
    E_BTL_UI_COMM_STEP_AUTO_BATTLE,
    E_BTL_UI_COMM_STEP_OPTION,
};

