#pragma once
#include "CoreMinimal.h"
#include "E_BTL_CAM_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_BTL_CAM_TYPE : uint8 {
    E_BTL_CAM_TYPE_NONE,
    E_BTL_CAM_TYPE_TURN_PREV_P,
    E_BTL_CAM_TYPE_TURN_PREV_E,
    E_BTL_CAM_TYPE_COMMAND,
    E_BTL_CAM_TYPE_START,
    E_BTL_CAM_TYPE_RESULT,
    E_BTL_CAM_TYPE_TARGET,
    E_BTL_CAM_TYPE_RECAM,
    E_BTL_CAM_TYPE_BADSTATUS,
    E_BTL_CAM_TYPE_BADSTATUS_ONE,
    E_BTL_CAM_TYPE_FUSION,
    E_BTL_CAM_TYPE_COMMAND_BACK,
    E_BTL_CAM_TYPE_COMMAND_FRONT,
    E_BTL_CAM_TYPE_SUMMON_SINGLE,
    E_BTL_CAM_TYPE_SUMMON_ALL,
    E_BTL_CAM_TYPE_ESCAPE,
    E_BTL_CAM_TYPE_N_COMMAND,
    E_BTL_CAM_TYPE_N_COMMAND_MENU,
    E_BTL_CAM_TYPE_TIAMAT_HEAD,
};

