#pragma once
#include "CoreMinimal.h"
#include "E_BTL_STAT.generated.h"

UENUM(BlueprintType)
enum class E_BTL_STAT : uint8 {
    E_BTL_STAT_BOSS,
    E_BTL_STAT_NOORDER,
    E_BTL_STAT_ENEMYFIRST,
    E_BTL_STAT_ENEMYTURN,
    E_BTL_STAT_PLAYERFIRST,
    E_BTL_STAT_TALK_SCOUT_SUCCESS,
    E_BTL_STAT_ENEMYPRESET,
    E_BTL_STAT_AUTO,
    E_BTL_STAT_WEAK_AUTO,
    E_BTL_STAT_GOTO_TITLE,
    E_BTL_STAT_PRESS_PLUS,
    E_BTL_STAT_STOP_TARSEL,
    E_BTL_STAT_ONCE_SUMMON_KAJYA,
    E_BTL_STAT_NOTACT_GUEST,
    E_BTL_STAT_TURN_REC_READY,
    E_BTL_STAT_TURN_REC,
    E_BTL_STAT_RENZOKU_ENCOUNT_TUTORIAL,
    E_BTL_STAT_TURNCHANGE,
    E_BTL_STAT_SYSTEMATIC,
    E_BTL_STAT_MUD_TUTORIAL,
    E_BTL_STAT_DARKNESS_TUTORIAL,
    E_BTL_STAT_ORDER_ENCOUNT,
    E_BTL_STAT_NOT_CRITICAL,
    E_BTL_STAT_SET_MAGATSUHI_DEVIL_DATA,
    E_BTL_STAT_SET_NEXT_ORDER,
    E_BTL_STAT_GUEST_ENTRY_EVENT,
    E_BTL_STAT_ENEMIES_TRUE_DAMAGE,
    E_BTL_STAT_PRESSICON_TURNSTART,
    E_BTL_STAT_RENZOKU_ENCOUNT_ENEMY,
    E_BTL_STAT_RENZOKU_ENCOUNT_TURN,
    E_BTL_STAT_ADD_PRESSICON_ENEMY_KILLED,
    E_BTL_STAT_NOPRESS,
};

