#pragma once
#include "CoreMinimal.h"
#include "E_BTL_PARTY_STAT2.generated.h"

UENUM(BlueprintType)
enum class E_BTL_PARTY_STAT2 : uint8 {
    E_BTL_PARTY_STAT2_REF_BARRIER,
    E_BTL_PARTY_STAT2_CHK_DMG_CHAR,
    E_BTL_PARTY_STAT2_HIT,
    E_BTL_PARTY_STAT2_HP1_UI,
    E_BTL_PARTY_STAT2_NOTACT,
    E_BTL_PARTY_STAT2_REC_COUNTER,
    E_BTL_PARTY_STAT2_TRUE_DAMAGE,
    E_BTL_PARTY_STAT2_UNIT_ACTIVE,
    E_BTL_PARTY_STAT2_ACT_COUNTER,
    E_BTL_PARTY_STAT2_ACT_PRE_CHECK,
    E_BTL_PARTY_STAT2_DEL_ELECTRIFICATION,
    E_BTL_PARTY_STAT2_REQ_DEAD,
    E_BTL_PARTY_STAT2_REQ_RETURN,
    E_BTL_PARTY_STAT2_REQ_RESULT,
    E_BTL_PARTY_STAT2_DONE_RESULT,
    E_BTL_PARTY_STAT2_DISABLED_AISHOU,
    E_BTL_PARTY_STAT2_NOT_ACTION,
    E_BTL_PARTY_STAT2_ENEMY_RETURN,
    E_BTL_PARTY_STAT2_GUEST,
    E_BTL_PARTY_STAT2_MAGATSUHI_DEVIL,
    E_BTL_PARTY_STAT2_DISABLED_AISHOU2,
};

