#pragma once
#include "CoreMinimal.h"
#include "E_BTL_COMM_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_BTL_COMM_TYPE : uint8 {
    E_BTL_COMM_NONE,
    E_BTL_COMM_ATTACK,
    E_BTL_COMM_SKILL,
    E_BTL_COMM_LEGIONSKILL,
    E_BTL_COMM_ESCAPE,
    E_BTL_COMM_DEFENCE,
    E_BTL_COMM_WAIT,
    E_BTL_COMM_TALK,
    E_BTL_COMM_ITEM,
    E_BTL_COMM_SUMMON,
    E_BTL_COMM_SUMMON2,
    E_BTL_COMM_RETURN,
    E_BTL_COMM_CALL,
    E_BTL_COMM_UNITE,
    E_BTL_COMM_ANALYZE,
    E_BTL_COMM_BADWAIT,
    E_BTL_COMM_SKIP,
    E_BTL_COMM_DAMAGE,
    E_BTL_COMM_UNION,
    E_BTL_COMM_PARTNER_WAIT,
    E_BTL_COMM_PARTNER_SUMMON_FAILED,
    E_BTL_COMM_CHANGE_ACTOR,
    E_BTL_COMM_EXCHANGE_HERO,
    E_BTL_COMM_AUTO_ON,
    E_BTL_COMM_UNION_BREAK,
    E_BTL_COMM_UPLIFTING,
};

