#pragma once
#include "CoreMinimal.h"
#include "E_BTL_PRESS_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_BTL_PRESS_TYPE : uint8 {
    E_BTL_PRESS_TYPE_NORMAL,
    E_BTL_PRESS_TYPE_WAIT,
    E_BTL_PRESS_TYPE_WEAK,
    E_BTL_PRESS_TYPE_CRITICAL,
    E_BTL_PRESS_TYPE_BADMISS,
    E_BTL_PRESS_TYPE_SKILLPRESS2,
    E_BTL_PRESS_TYPE_MISS,
    E_BTL_PRESS_TYPE_BLOCK,
    E_BTL_PRESS_TYPE_REFLEX,
    E_BTL_PRESS_TYPE_ABSORB,
    E_BTL_PRESS_TYPE_MUD,
    E_BTL_PRESS_TYPE_ESC,
    E_BTL_PRESS_TYPE_RETURN,
    E_BTL_PRESS_TYPE_SUMMON,
    E_BTL_PRESS_TYPE_TALK_OK,
    E_BTL_PRESS_TYPE_TALK_OK2,
    E_BTL_PRESS_TYPE_TALK_NG1,
    E_BTL_PRESS_TYPE_TALK_NG2,
    E_BTL_PRESS_TYPE_TURN,
    E_BTL_PRESS_TYPE_ADD1,
    E_BTL_PRESS_TYPE_ADD2,
    E_BTL_PRESS_TYPE_ADD3,
    E_BTL_PRESS_TYPE_ADD4,
    E_BTL_PRESS_TYPE_SUB1,
    E_BTL_PRESS_TYPE_SUB2,
    E_BTL_PRESS_TYPE_SUB3,
    E_BTL_PRESS_TYPE_SUB4,
    E_BTL_PRESS_TYPE_ADD1_ITEM,
    E_BTL_PRESS_TYPE_ADDMAX_ITEM,
    E_BTL_PRESS_TYPE_TURNSTART,
    E_BTL_PRESS_TYPE_SETMAX,
    E_BTL_PRESS_TYPE_BACKUP,
    E_BTL_PRESS_TYPE_BACKUP_ADDED,
    E_BTL_PRESS_TYPE_NOT,
};

