#pragma once
#include "CoreMinimal.h"
#include "E_BTL_STAT_2.generated.h"

UENUM(BlueprintType)
enum class E_BTL_STAT_2 : uint8 {
    E_BTL_STAT_2_NEXT_HIT_UP,
    E_BTL_STAT_2_NEXT_CRI_UP,
    E_BTL_STAT_2_TURN_FIRST_ACT_P,
    E_BTL_STAT_2_INOCHIGOI_CALC,
    E_BTL_STAT_2_UPLIFTING_TURN,
    E_BTL_STAT_2_CANCEL_SKILLINFO,
    E_BTL_STAT_2_UPLIFTING_OFF,
    E_BTL_STAT_2_EVENT,
    E_BTL_STAT_2_START_CHARM_OR_CONFUSE,
    E_BTL_STAT_2_ENEMY_MAGATSUHI_OFF,
    E_BTL_STAT_2_NOT_CHANGE_ORDER,
    E_BTL_STAT_2_ACT_PRE_CAM_CHANGE,
    E_BTL_STAT_2_SHARE_HP_RATE,
    E_BTL_STAT_2_ENEMYTURNEND_SKILL,
    E_BTL_STAT_2_EVENT_2,
    E_BTL_STAT_2_TURN_CHK_EFFECT,
    E_BTL_STAT_2_KEEP_SKILL_MENU,
    E_BTL_STAT_2_TURN_CHK_BST_ACT_END,
    E_BTL_STAT_2_TURN_CHK_PREV,
    E_BTL_STAT_2_TURN_CHK_CURE,
    E_BTL_STAT_2_TURN_CHK_BST_CURE,
    E_BTL_STAT_2_TURN_CHK_BST_DAM,
    E_BTL_STAT_2_TURN_CHK_BST_DAM2,
    E_BTL_STAT_2_CHANGE_ACTOR,
    E_BTL_STAT_2_COUNTER_TURN_CHANGE,
    E_BTL_STAT_2_FAILED_ESCAPE,
    E_BTL_STAT_2_COUNTER_TURN_CHANGE_EFT_END,
    E_BTL_STAT_2_RE_CHANGE_ACTOR,
    E_BTL_STAT_2_ACT_EXHANGE,
    E_BTL_STAT_2_DEL_ALL_ELECTRIFICATION,
    E_BTL_STAT_2_PRESS_ICON_FULL,
    E_BTL_STAT_2_REQ_ALL_RETURN,
};

