#pragma once
#include "CoreMinimal.h"
#include "E_BTL_PANEL_CTRL.generated.h"

UENUM(BlueprintType)
enum class E_BTL_PANEL_CTRL : uint8 {
    E_BTL_PANEL_CTRL_ADD_HP,
    E_BTL_PANEL_CTRL_ADD_MP,
    E_BTL_PANEL_CTRL_ADD_BST,
    E_BTL_PANEL_CTRL_SET_HP,
    E_BTL_PANEL_CTRL_SET_MP,
    E_BTL_PANEL_CTRL_SET_BST,
    E_BTL_PANEL_CTRL_SET_MAXHP,
    E_BTL_PANEL_CTRL_SET_MAXMP,
    E_BTL_PANEL_CTRL_SET_EMPTY,
    E_BTL_PANEL_CTRL_SET_ACTOR,
    E_BTL_PANEL_CTRL_SET_TARGET,
    E_BTL_PANEL_CTRL_SET_ACT_END,
    E_BTL_PANEL_CTRL_SET_TURN_CHANGE,
    E_BTL_PANEL_CTPL_SET_HP_FORECAST,
    E_BTL_PANEL_CTPL_SET_MP_FORECAST,
    E_BTL_PANEL_CTRL_SET_VIRTUAL_ORDER,
    E_BTL_PANEL_CTRL_SET_AID_PARAM,
    E_BTL_PANEL_CTRL_OOMAGATOKI,
    E_BTL_PANEL_CTRL_DEAD_KUISHIBARI,
    E_BTL_PANEL_CTRL_UPDATE_BST,
    E_BTL_PANEL_CTRL_SET_VISIBILITY,
    E_BTL_PANEL_CTRL_COST_MP,
};

