#pragma once
#include "CoreMinimal.h"
#include "E_BTL_SKILL_CAM_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_BTL_SKILL_CAM_TYPE : uint8 {
    E_BTL_SKILL_CAM_TYPE_ACTOR,
    E_BTL_SKILL_CAM_TYPE_TARGET,
    E_BTL_SKILL_CAM_TYPE_ORIGIN,
    E_BTL_SKILL_CAM_TYPE_ACTOR_ALL,
    E_BTL_SKILL_CAM_TYPE_TARGET_ALL,
    E_BTL_SKILL_CAM_TYPE_REFLECTION,
    E_BTL_SKILL_CAM_TYPE_REFLECTION_ALL,
};

