#pragma once
#include "CoreMinimal.h"
#include "E_BTL_PARTY_STAT.generated.h"

UENUM(BlueprintType)
enum class E_BTL_PARTY_STAT : uint8 {
    E_BTL_PARTY_STAT_EXIST,
    E_BTL_PARTY_STAT_HERO,
    E_BTL_PARTY_STAT_NAKAMA,
    E_BTL_PARTY_STAT_ENEMY,
    E_BTL_PARTY_STAT_PARTNER,
    E_BTL_PARTY_STAT_ACTEND,
    E_BTL_PARTY_STAT_LOST,
    E_BTL_PARTY_STAT_STOCK,
    E_BTL_PARTY_STAT_LEADER,
    E_BTL_PARTY_STAT_BOY,
    E_BTL_PARTY_STAT_AOGAMI,
    E_BTL_PARTY_STAT_ACTEND_FINISHED,
    E_BTL_PARTY_STAT_CRITICAL,
    E_BTL_PARTY_STAT_KUIUSE,
    E_BTL_PARTY_STAT_KUIUSE2,
    E_BTL_PARTY_STAT_BUDDY,
    E_BTL_PARTY_STAT_UNION_HERO,
    E_BTL_PARTY_STAT_ENEMY_SUMMON,
    E_BTL_PARTY_STAT_HIT_TARGET,
    E_BTL_PARTY_STAT_APPLY_UNIT_STATE,
    E_BTL_PARTY_STAT_DEFENSE,
    E_BTL_PARTY_STAT_TALKED_BEGLIFE,
    E_BTL_PARTY_STAT_NEXTACT,
    E_BTL_PARTY_STAT_FUJIMI,
    E_BTL_PARTY_STAT_CANCEL_DEAD,
    E_BTL_PARTY_STAT_NO_DESTROY_MODEL,
    E_BTL_PARTY_STAT_ITEM_DROP,
    E_BTL_PARTY_STAT_DEAD_EVENT,
    E_BTL_PARTY_STAT_CHECKED_BEGLIFE,
    E_BTL_PARTY_STAT_CANACT,
    E_BTL_PARTY_STAT_AVOID,
    E_BTL_PARTY_STAT_MISS,
};

