#pragma once
#include "CoreMinimal.h"
#include "E_BTL_DEAD_EFFECT.generated.h"

UENUM(BlueprintType)
enum class E_BTL_DEAD_EFFECT : uint8 {
    E_BTL_DEAD_EFFECT_NORMAL,
    E_BTL_DEAD_EFFECT_FIRE,
    E_BTL_DEAD_EFFECT_ICE,
    E_BTL_DEAD_EFFECT_THUNDER,
    E_BTL_DEAD_EFFECT_WIND,
    E_BTL_DEAD_EFFECT_LIGHT,
    E_BTL_DEAD_EFFECT_DARK,
    E_BTL_DEAD_EFFECT_ALL,
    E_BTL_DEAD_EFFECT_VARTICAL,
    E_BTL_DEAD_EFFECT_HORIZONAL,
    E_BTL_DEAD_EFFECT_PHYSICS,
    E_BTL_DEAD_EFFECT_STONE,
};

