#pragma once
#include "CoreMinimal.h"
#include "E_CAMP_TOPMENU_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_CAMP_TOPMENU_TYPE : uint8 {
    E_CAMP_TOPMENU_TYPE_SKILL,
    E_CAMP_TOPMENU_TYPE_ITEM,
    E_CAMP_TOPMENU_TYPE_PARTY,
    E_CAMP_TOPMENU_TYPE_GOD,
    E_CAMP_TOPMENU_TYPE_MISSION,
    E_CAMP_TOPMENU_TYPE_DDS,
    E_CAMP_TOPMENU_TYPE_DATABASE,
    E_CAMP_TOPMENU_TYPE_JAKYO,
};

