#pragma once
#include "CoreMinimal.h"
#include "E_CAMP_COMMAND_ID.generated.h"

UENUM(BlueprintType)
enum class E_CAMP_COMMAND_ID : uint8 {
    E_CAMP_COMMAND_ID_DAMMY,
    E_CAMP_COMMAND_ID_SKILL,
    E_CAMP_COMMAND_ID_SKILL_LIB,
    E_CAMP_COMMAND_ID_ITEM,
    E_CAMP_COMMAND_ID_PARTY,
    E_CAMP_COMMAND_ID_PROPERTY,
    E_CAMP_COMMAND_ID_PARTNER,
    E_CAMP_COMMAND_ID_QUEST,
    E_CAMP_COMMAND_ID_DATA_BASE,
    E_CAMP_COMMAND_ID_CHARACTERS,
    E_CMAP_COMMAND_ID_UNIT,
    E_CAMP_COMMAND_ID_DDS,
};

