#pragma once
#include "CoreMinimal.h"
#include "E_CHARAPANELBASE.generated.h"

UENUM(BlueprintType)
enum class E_CHARAPANELBASE : uint8 {
    E_CHARAPANELBASE_BADSTATUS_MAX = 2 UMETA(Hidden),
    E_CHARAPANELBASE_SUPPORT_MAX = 8 UMETA(Hidden),
    E_CHARAPASNELBASE_PANELTYPE_NORMAL = 0,
    E_CHARAPASNELBASE_PANELTYPE_STOCK_EMPTY,
    E_CHARAPASNELBASE_PANELTYPE_PARTY_EMPTY = E_CHARAPANELBASE_BADSTATUS_MAX,
    E_CHARAPASNELBASE_PANELTYPE_NON,
};

