#pragma once
#include "CoreMinimal.h"
#include "E_CHARAPANEL_SUPPORTICON_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_CHARAPANEL_SUPPORTICON_TYPE : uint8 {
    CP_SUPPORTICON_TYPE_NONE,
    CP_SUPPORTICON_TYPE_ATTACK_UP1,
    CP_SUPPORTICON_TYPE_ATTACK_UP2,
    CP_SUPPORTICON_TYPE_DEFENCE_UP1,
    CP_SUPPORTICON_TYPE_DEFENCE_UP2,
    CP_SUPPORTICON_TYPE_AVOID_UP1,
    CP_SUPPORTICON_TYPE_AVOID_UP2,
    CP_SUPPORTICON_TYPE_ATTACK_DOWN1,
    CP_SUPPORTICON_TYPE_ATTACK_DOWN2,
    CP_SUPPORTICON_TYPE_DEFENCE_DOWN1,
    CP_SUPPORTICON_TYPE_DEFENCE_DOWN2,
    CP_SUPPORTICON_TYPE_AVOID_DOWN1,
    CP_SUPPORTICON_TYPE_AVOID_DOWN2,
    CP_SUPPORTICON_TYPE_REFLECTION_PHYSICS,
    CP_SUPPORTICON_TYPE_REFLECTION_MAGIC,
    CP_SUPPORTICON_TYPE_AVOIDDEATH,
    CP_SUPPORTICON_TYPE_CHARGE_PHYSICS,
    CP_SUPPORTICON_TYPE_CHARGE_MAGIC,
    CP_SUPPORTICON_TYPE_CHARGE_CRITICAL,
    CP_SUPPORTICON_TYPE_CHARGE_RECOVERY,
    CP_SUPPORTICON_TYPE_CHARGE_DISABLE,
    CP_SUPPORTICON_TYPE_PROVOKE,
    CP_SUPPORTICON_TYPE_BARRIER_PHYSICS,
    CP_SUPPORTICON_TYPE_BARRIER_FIRE,
    CP_SUPPORTICON_TYPE_BARRIER_ICE,
    CP_SUPPORTICON_TYPE_BARRIER_THUNDER,
    CP_SUPPORTICON_TYPE_BARRIER_WIND,
    CP_SUPPORTICON_TYPE_BARRIER_LIGHT,
    CP_SUPPORTICON_TYPE_BARRIER_DARK,
    CP_SUPPORTICON_TYPE_BARRIER_ALLCUT,
    CP_SUPPORTICON_TYPE_MAGATOKI,
    CP_SUPPORTICON_TYPE_RENGEKI,
    CP_SUPPORTICON_TYPE_A_AVOID,
};

