#pragma once
#include "CoreMinimal.h"
#include "E_DEFENCE_RESISTANCE.generated.h"

UENUM(BlueprintType)
enum class E_DEFENCE_RESISTANCE : uint8 {
    E_DEFENCE_RESISTANCE_WEAK,
    E_DEFENCE_RESISTANCE_NORMAL,
    E_DEFENCE_RESISTANCE_RESIST,
    E_DEFENCE_RESISTANCE_BLOCK,
    E_DEFENCE_RESISTANCE_REFRECT,
    E_DEFENCE_RESISTANCE_ABSORB,
};

