#pragma once
#include "CoreMinimal.h"
#include "E_ENDURE_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_ENDURE_TYPE : uint8 {
    E_ENDURE_TYPE_NONE,
    E_ENDURE_TYPE_PHYSICAL,
    E_ENDURE_TYPE_FIRE,
    E_ENDURE_TYPE_ICE,
    E_ENDURE_TYPE_THUNDER,
    E_ENDURE_TYPE_WIND,
    E_ENDURE_TYPE_LIGHT,
    E_ENDURE_TYPE_DARK,
    E_ENDURE_TYPE_ALL,
    E_ENDURE_TYPE_POISON,
    E_ENDURE_TYPE_VERTIGO,
    E_ENDURE_TYPE_CONFUSE,
    E_ENDURE_TYPE_CHARM,
    E_ENDURE_TYPE_SLEEP,
    E_ENDURE_TYPE_CLOSE,
    E_ENDURE_TYPE_STRAY,
    E_ENDURE_TYPE_BURN,
    E_ENDURE_TYPE_FREEZE,
    E_ENDURE_TYPE_SHOCK,
    E_ENDURE_TYPE_LACERATION,
    E_ENDURE_TYPE_STONE,
    E_ENDURE_TYPE_DAZZLE,
};

