#pragma once
#include "CoreMinimal.h"
#include "E_GODPARAMETER_STATE.generated.h"

UENUM(BlueprintType)
enum class E_GODPARAMETER_STATE : uint8 {
    E_GODPARAMETER_STATE_INVALID_ID,
    E_GODPARAMETER_STATE_NOT_DISPLAY,
    E_GODPARAMETER_STATE_NOT_PRIMISE_SKILL,
    E_GODPARAMETER_STATE_NOT_ENOUGH_POINT,
    E_GODPARAMETER_STATE_ENABLE_LEARNING,
    E_GODPARAMETER_STATE_ALREADY_LEARNING,
};

