#pragma once
#include "CoreMinimal.h"
#include "E_HEALCHARAPANELCTRL_GSTATUS.generated.h"

UENUM(BlueprintType)
enum class E_HEALCHARAPANELCTRL_GSTATUS : uint8 {
    E_HEALCHARAPANELCTRL_INIT,
    E_HEALCHARAPANELCTRL_CREATE_TARGETSELECT,
    E_HEALCHARAPANELCTRL_SELECTTARGET,
    E_HEALCHARAPANELCTRL_HEAL,
    E_HEALCHARAPANELCTRL_WAIT_ENDHEAL,
    E_HEALCHARAPANELCTRL_ENDHEAL,
    E_HEALCHARAPANELCTRL_SET_ERROR,
    E_HEALCHARAPANELCTRL_WAIT_ERROR,
    E_HEALCHARAPANELCTRL_SELECTALL_ON,
    E_HEALCHARAPANELCTRL_SELECT_ALL,
    E_HEALCHARAPANELCTRL_HEALALL,
    E_HEALCHARAPANELCTRL_WAIT_HEALALL,
    E_HEALCHARAPANELCTRL_STATUSDETAILINIT,
    E_HEALCHARAPANELCTRL_STATUSDETAIL,
    E_HEALCHARAPANELCTRL_HEALT_WAITMESSAGE,
    E_HEALCHARAPANELCTRL_SINGLEHEAL,
};

