#pragma once
#include "CoreMinimal.h"
#include "E_ICON_SPR_ID.generated.h"

UENUM(BlueprintType)
enum class E_ICON_SPR_ID : uint8 {
    E_ICON_SPR_ID_PHYSICS,
    E_ICON_SPR_ID_FIRE,
    E_ICON_SPR_ID_ICE,
    E_ICON_SPR_ID_THUNDER,
    E_ICON_SPR_ID_WIND,
    E_ICON_SPR_ID_LIGHT,
    E_ICON_SPR_ID_DARK,
    E_ICON_SPR_ID_EVERY,
    E_ICON_SPR_ID_BST,
    E_ICON_SPR_ID_CURE,
    E_ICON_SPR_ID_AID,
    E_ICON_SPR_ID_SP,
    E_ICON_SPR_ID_AUTO,
    E_ICON_SPR_ID_SHIELD,
    E_ICON_SPR_ID_QUESTION,
    E_ICON_SPR_ID_TAB,
    E_ICON_SPR_ID_PARAM_UP,
    E_ICON_SPR_ID_SKILL_GET,
    E_ICON_SPR_ID_PUROPATRY_UP,
    E_ICON_SPR_ID_DELIVERTY,
    E_ICON_SPR_ID_RELIC,
    E_ICON_SPR_ID_VALUABLES,
    E_ICON_SPR_ID_ALL,
    E_ICON_SPR_ID_COMPOSITE,
    E_ICON_SPR_ID_TALK,
    E_ICON_SPR_ID_DUMMY25,
    E_ICON_SPR_ID_DUMMY26,
    E_ICON_SPR_ID_DUMMY27,
    E_ICON_SPR_ID_DUMMY28,
    E_ICON_SPR_ID_DUMMY29,
    E_ICON_SPR_ID_DUMMY30,
    E_ICON_SPR_ID_DUMMY31,
};

