#pragma once
#include "CoreMinimal.h"
#include "E_ITEM_ICON_ID.generated.h"

UENUM(BlueprintType)
enum class E_ITEM_ICON_ID : uint8 {
    E_ITEM_ICON_ID_DUMMY,
    E_ITEM_ICON_ID_CURE,
    E_ITEM_ICON_ID_SKILL_PHYSICS,
    E_ITEM_ICON_ID_SKILL_FIRE,
    E_ITEM_ICON_ID_SKILL_ICE,
    E_ITEM_ICON_ID_SKILL_THUNDER,
    E_ITEM_ICON_ID_SKILL_WIND,
    E_ITEM_ICON_ID_SKILL_LIGHT,
    E_ITEM_ICON_ID_SKILL_DARK,
    E_ITEM_ICON_ID_SKILL_EVERY,
    E_ITEM_ICON_ID_SKILL_BST,
    E_ITEM_ICON_ID_SKILL_CURE,
    E_ITEM_ICON_ID_SKILL_AID,
    E_ITEM_ICON_ID_SKILL_SP,
    E_ITEM_ICON_PARAM_UP,
    E_ITEM_ICON_SKILL_GET,
    E_ITEM_ICON_PUROPATRY_UP,
    E_ITEM_ICON_DELIVERTY,
    E_ITEM_ICON_RELIC,
    E_ITEM_ICON_VALUABLES,
};

