#pragma once
#include "CoreMinimal.h"
#include "E_ITEM_USECONDITION.generated.h"

UENUM(BlueprintType)
enum class E_ITEM_USECONDITION : uint8 {
    E_ITEM_USECONDITION_NONE,
    E_ITEM_USECONDITION_GOTOMAP,
    E_ITEM_USECONDITION_ENCOUNTOFF,
    E_ITEM_USECONDITION_CHANGETEKISEI,
    E_ITEM_USECONDITION_REPLACEMENTTEKISEI,
    E_ITEM_USECONDITION_CHANGEGODPARAMETER,
    E_ITEM_USECONDITION_KUISHIBARI,
    E_ITEM_USECONDITION_RENZOKU_UP,
    E_ITEM_USECONDITION_CHANGEPARAMETER,
    E_ITEM_USECONDITION_NOTSELECTED_MULTIPLE,
};

