#pragma once
#include "CoreMinimal.h"
#include "E_ITEM_ENABLE_SCENE.generated.h"

UENUM(BlueprintType)
enum class E_ITEM_ENABLE_SCENE : uint8 {
    E_SKILL_ENABLE_SCENE_NOT_USE,
    E_SKILL_ENABLE_SCENE_FIELD,
    E_SKILL_ENABLE_SCENE_BATTLE,
    E_SKILL_ENABLE_SCENE_FACILITY,
    E_SKILL_ENABLE_SCENE_NOT_BATTLE,
    E_SKILL_ENABLE_SCENE_NOT_FIELD,
    E_SKILL_ENABLE_SCENE_NOT_FACILITY,
    E_SKILL_ENABLE_SCENE_ALL_SCENE,
};

