#pragma once
#include "CoreMinimal.h"
#include "E_KUISHIBARI_LEVEL.generated.h"

UENUM(BlueprintType)
enum class E_KUISHIBARI_LEVEL : uint8 {
    E_KUISHIBARI_LEVEL_NONE,
    E_KUISHIBARI_LEVEL_HPONE,
    E_KUISHIBARI_LEVEL_HPFULL,
    E_KUISHIBARI_LEVEL_HPONEGIFT,
    E_KUISHIBARI_LEVEL_HPFULL_ITEM,
    E_KUISHIBARI_LEVEL_HERO_HPFULL_STOCK,
    E_KUISHIBARI_LEVEL_HPFULL_STOCK,
    E_KUISHIBARI_LEVEL_HPONE_RAND,
    E_KUISHIBARI_LEVEL_HPFULL_ABS,
};

