#pragma once
#include "CoreMinimal.h"
#include "E_LVUPMANAGER_GSTATUS.generated.h"

UENUM(BlueprintType)
enum class E_LVUPMANAGER_GSTATUS : uint8 {
    E_LVUPMANAGER_GSTATUS_EMPTY,
    E_LVUPMANAGER_GSTATUS_SHOW_UP_PARAM,
    E_LVUPMANAGER_GSTATUS_PARAM_ALLOCATE,
    E_LVUPMANAGER_GSTATUS_PARAM_ALLOCATE_MESSAGE,
    E_LVUPMANAGER_GSTATUS_WAIT_BEFORE_REICHI,
    E_LVUPMANAGER_GSTATUS_GET_REICHI,
    E_LVUPMANAGER_GSTATUS_SKILL_MESSAGE,
    E_LVUPMANAGER_GSTATUS_SKILL_SELECT,
    E_LVUPMANAGER_GSTATUS_SKILL_SET_ANIMATION,
    E_LVUPMANAGER_GSTATUS_SKILL_DISCARD_MESSAGE,
    E_LVUPMANAGER_GSTATUS_SKILL_DECIDE_MESSAGE,
    E_LVUPMANAGER_GSTATUS_EX_SKILL,
    E_LVUPMANAGER_GSTATUS_BEFORE_GIFT,
    E_LVUPMANAGER_GSTATUS_GIFT,
    E_LVUPMANAGER_GSTATUS_GIFT_SYSTEM_MESSAGE,
    E_LVUPMANAGER_GSTATUS_FLASH_NEXT_SKILLS,
    E_LVUPMANAGER_GSTATUS_SKILL_DISCARD_START_MESSAGE,
    E_LVUPMANAGER_GSTATUS_ALLOCATE_START_MESSAGE,
    E_LVUPMANAGER_GSTATUS_ALLOCATE_NOT_YET_MESSAGE,
    E_LVUPMANAGER_GSTATUS_GARDEN_SHOW_STATUS,
    E_LVUPMANAGER_GSTATUS_GARDEN_TEKISEI_UP_MESSAGE,
    E_LVUPMANAGER_GSTATUS_GARDEN_PARAM_UP_MESSAGE,
    E_LVUPMANAGER_GSTATUS_GARDEN_ALLOCATE_START_MESSAGE,
    E_LVUPMANAGER_GSTATUS_GARDEN_PARAM_ALLOCATE,
    E_LVUPMANAGER_GSTATUS_GARDEN_ALLOCATE_NOT_YET_MESSAGE,
    E_LVUPMANAGER_GSTATUS_GARDEN_PARAM_ALLOCATE_MESSAGE,
};

