#pragma once
#include "CoreMinimal.h"
#include "E_MIMAN_REWARD_ITEMSET.generated.h"

UENUM(BlueprintType)
enum class E_MIMAN_REWARD_ITEMSET : uint8 {
    E_MIMAN_REWARD_ITEMSET_DUMMY,
    E_MIMAN_REWARD_ITEMSET_00,
    E_MIMAN_REWARD_ITEMSET_01,
    E_MIMAN_REWARD_ITEMSET_02,
    E_MIMAN_REWARD_ITEMSET_03,
    E_MIMAN_REWARD_ITEMSET_04,
    E_MIMAN_REWARD_ITEMSET_05,
    E_MIMAN_REWARD_ITEMSET_06,
    E_MIMAN_REWARD_ITEMSET_07,
    E_MIMAN_REWARD_ITEMSET_08,
    E_MIMAN_REWARD_ITEMSET_09,
    E_MIMAN_REWARD_ITEMSET_10,
    E_MIMAN_REWARD_ITEMSET_11,
    E_MIMAN_REWARD_ITEMSET_12,
    E_MIMAN_REWARD_ITEMSET_13,
    E_MIMAN_REWARD_ITEMSET_14,
    E_MIMAN_REWARD_ITEMSET_15,
    E_MIMAN_REWARD_ITEMSET_16,
    E_MIMAN_REWARD_ITEMSET_17,
    E_MIMAN_REWARD_ITEMSET_18,
};

