#pragma once
#include "CoreMinimal.h"
#include "E_MISSION_COND_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_MISSION_COND_TYPE : uint8 {
    E_MISSION_COND_NONE,
    E_MISSION_COND_HUNT,
    E_MISSION_COND_ITEM,
    E_MISSION_COND_FLAG,
    E_MISSION_COND_COUNT,
    E_MISSION_COND_NAKAMA,
    E_MISSION_COND_NAKAMA_LEVEL,
    E_MISSION_COND_NAKAMA_SKILL,
    E_MISSION_COND_PLAYER_SKILL,
    E_MISSION_COND_COUNT_ONLY,
    E_MISSION_COND_GROUP_HUNT,
    E_MISSION_COND_GOD,
};

