#pragma once
#include "CoreMinimal.h"
#include "E_MINIMAP_POI_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_MINIMAP_POI_TYPE : uint8 {
    E_MINIMAP_POI_TYPE_NONE,
    E_MINIMAP_POI_TYPE_ENEMY,
    E_MINIMAP_POI_TYPE_MISSION,
    E_MINIMAP_POI_TYPE_ACTOR,
    E_MINIMAP_POI_TYPE_MAGATSUKA,
    E_MINIMAP_POI_TYPE_RYUKETSU,
    E_MINIMAP_POI_TYPE_GOD,
    E_MINIMAP_POI_TYPE_TREASURE,
    E_MINIMAP_POI_TYPE_DOOR,
    E_MINIMAP_POI_TYPE_DG_OBJ,
    E_MINIMAP_POI_TYPE_TIME_STOP,
    E_MINIMAP_POI_TYPE_TIME_MOVE,
    E_MINIMAP_POI_TYPE_MIMAN,
    E_MINIMAP_POI_TYPE_RELIC,
    E_MINIMAP_POI_TYPE_CHANGE_AREA,
    E_MINIMAP_POI_TYPE_CLIMB_POINT,
    E_MINIMAP_POI_TYPE_DEVIL_STATUE,
    E_MINIMAP_POI_TYPE_GARDEN_DEVIL,
    E_MINIMAP_POI_TYPE_ROTATE_SWITCH,
    E_MINIMAP_POI_TYPE_DOOR_SWITCH,
    E_MINIMAP_POI_TYPE_COASTER,
    E_MINIMAP_POI_TYPE_AOGAMI_DEBRIS,
    E_MINIMAP_POI_TYPE_LANDMARK,
};

