#pragma once
#include "CoreMinimal.h"
#include "E_NAVI_DEVIL.generated.h"

UENUM(BlueprintType)
enum class E_NAVI_DEVIL : uint8 {
    E_NAVI_DEVIL_NONE,
    E_NAVI_DEVIL_DEV059_PIXIE,
    E_NAVI_DEVIL_DEV114_AITVARAS,
    E_NAVI_DEVIL_DEV057_JACKOLANTERN,
    E_NAVI_DEVIL_DEV273_DECARABIA,
    E_NAVI_DEVIL_DEV280_YATAGARASU,
    E_NAVI_DEVIL_DEV333_KAHAKU,
    E_NAVI_DEVIL_DEV038_AMANOZAKO,
    E_NAVI_DEVIL_DEV128_CIRONNUP,
    E_NAVI_DEVIL_DEV289_MOSHOBOU,
    E_NAVI_DEVIL_DEV060_NAHOBIHO,
    E_NAVI_DEVIL_DEV355_ALICE,
    E_NAVI_DEVIL_DEV387_AMABIE,
    E_NAVI_DEVIL_DEV191_CYBELE,
    E_NAVI_DEVIL_DEV316_IPPONDATARA,
    E_NAVI_DEVIL_DEV144_BAGS,
    E_NAVI_DEVIL_DEV304_MERMAID,
    E_NAVI_DEVIL_DEV067_LILIM,
    E_NAVI_DEVIL_DEV214_SUKUNAHIKONA,
    E_NAVI_DEVIL_DEV044_AGATHION,
    E_NAVI_DEVIL_DEV077_MARA,
    E_NAVI_DEVIL_DEV023_ITHUNN,
    E_NAVI_DEVIL_DEV147_MOTHMAN,
    E_NAVI_DEVIL_DEV035_FIONNMACCUMHAILL,
    E_NAVI_DEVIL_DEV356_HELLSANGEL,
    E_NAVI_DEVIL_DEV295_CLEOPATRA,
};

