#pragma once
#include "CoreMinimal.h"
#include "E_NAHOBINO_SKILL_MOTION.generated.h"

UENUM(BlueprintType)
enum class E_NAHOBINO_SKILL_MOTION : uint8 {
    E_NAHOBINO_SKILL_MOTION_NONE,
    E_NAHOBINO_SKILL_MOTION_RANGED,
    E_NAHOBINO_SKILL_MOTION_CLOSE_SWORD,
    E_NAHOBINO_SKILL_MOTION_CLOSE_FIST,
    E_NAHOBINO_SKILL_MOTION_SUPPORT,
    E_NAHOBINO_SKILL_MOTION_ATTACK,
};

