#pragma once
#include "CoreMinimal.h"
#include "E_OPTION_CONTENT_BUTTON_ICON_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_OPTION_CONTENT_BUTTON_ICON_TYPE : uint8 {
    E_OPTION_CONTENT_BUTTON_ICON_TYPE_DEFAULT,
    E_OPTION_CONTENT_BUTTON_ICON_TYPE_SWITCH,
    E_OPTION_CONTENT_BUTTON_ICON_TYPE_PS4,
    E_OPTION_CONTENT_BUTTON_ICON_TYPE_PS5,
    E_OPTION_CONTENT_BUTTON_ICON_TYPE_XBOX,
};

