#pragma once
#include "CoreMinimal.h"
#include "E_OPTION_ADDITIONAL_RESPONCE.generated.h"

UENUM(BlueprintType)
enum class E_OPTION_ADDITIONAL_RESPONCE : uint8 {
    E_OPTION_ADDITIONAL_RESPONCE_NONE,
    E_OPTION_ADDITIONAL_RESPONCE_PLAY_VOICE,
    E_OPTION_ADDITIONAL_RESPONCE_DIFFICULTY_TUTORIAL,
    E_OPTION_ADDITIONAL_RESPONCE_SKILL_SPEED_TUTORIAL,
};

