#pragma once
#include "CoreMinimal.h"
#include "E_OPTION_CONTENT_BATTLE_ACTION_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_OPTION_CONTENT_BATTLE_ACTION_TYPE : uint8 {
    E_OPTION_CONTENT_BATTLE_ACTION_TYPE_ATTACK,
    E_OPTION_CONTENT_BATTLE_ACTION_TYPE_SKILL,
    E_OPTION_CONTENT_BATTLE_ACTION_TYPE_SELECT_AT_START,
};

