#pragma once
#include "CoreMinimal.h"
#include "E_OPTION_CONTENT_ITEM_PRIORITIZE_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_OPTION_CONTENT_ITEM_PRIORITIZE_TYPE : uint8 {
    E_OPTION_CONTENT_ITEM_PRIORITIZE_TYPE_HEAL,
    E_OPTION_CONTENT_ITEM_PRIORITIZE_TYPE_ATTACK,
    E_OPTION_CONTENT_ITEM_PRIORITIZE_TYPE_ASSIST,
    E_OPTION_CONTENT_ITEM_PRIORITIZE_TYPE_SPECIAL,
};

