#pragma once
#include "CoreMinimal.h"
#include "E_OPTION_BATTLE_PRODUCTION_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_OPTION_BATTLE_PRODUCTION_TYPE : uint8 {
    E_OPTION_BATTLE_PRODUCTION_TYPE_A_BUTTON,
    E_OPTION_BATTLE_PRODUCTION_TYPE_ALWAYS,
    E_OPTION_BATTLE_PRODUCTION_TYPE_INVALID,
};

