#pragma once
#include "CoreMinimal.h"
#include "E_OPTION_CONTENT_FRAME_RATE_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_OPTION_CONTENT_FRAME_RATE_TYPE : uint8 {
    E_OPTION_CONTENT_FRAME_RATE_TYPE_UNLIMITED,
    E_OPTION_CONTENT_FRAME_RATE_TYPE_30 = 30,
    E_OPTION_CONTENT_FRAME_RATE_TYPE_60 = 60,
    E_OPTION_CONTENT_FRAME_RATE_TYPE_90 = 90,
    E_OPTION_CONTENT_FRAME_RATE_TYPE_120 = 120,
    E_OPTION_CONTENT_FRAME_RATE_TYPE_144 = 144,
};

