#pragma once
#include "CoreMinimal.h"
#include "E_OPTION_CONTENT_STICK_PUSH_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_OPTION_CONTENT_STICK_PUSH_TYPE : uint8 {
    E_OPTION_CONTENT_STICK_PUSH_TYPE_NONE,
    E_OPTION_CONTENT_STICK_PUSH_TYPE_AUTO_DASH,
    E_OPTION_CONTENT_STICK_PUSH_TYPE_CAMERA_RESET,
};

