#pragma once
#include "CoreMinimal.h"
#include "E_OVERWRITE_CONDITION.generated.h"

UENUM(BlueprintType)
enum class E_OVERWRITE_CONDITION : uint8 {
    E_OVERWRITE_CONDITION_NONE,
    E_OVERWRITE_CONDITION_UPLIFTING,
    E_OVERWRITE_CONDITION_WEAK,
    E_OVERWRITE_CONDITION_CRITICAL,
    E_OVERWRITE_CONDITION_TARGET_BST,
    E_OVERWRITE_CONDITION_CALC_ATTACK_CNT,
    E_OVERWRITE_CONDITION_MP_CURE,
};

