#pragma once
#include "CoreMinimal.h"
#include "E_SHOP_ITEM_SORT_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_SHOP_ITEM_SORT_TYPE : uint8 {
    E_SHOP_ITEM_SORT_KIND,
    E_SHOP_ITEM_SORT_ITEM_NUM,
    E_SHOP_ITEM_SORT_NEW,
    E_SHOP_ITEM_SORT_BUYING_PRICE,
    E_SHOP_ITEM_SORT_SELLING_PRICE,
    E_SHOP_ITEM_SORT_UTSUSEMI,
    E_SHOP_ITEM_SORT_UTSUSEMI_NUM,
    E_SHOP_ITEM_SORT_UTSUSEMI_NEW,
    E_SHOP_ITEM_SORT_UTSUSEMI_BUYING_PRICE,
};

