#pragma once
#include "CoreMinimal.h"
#include "E_SKILL_MASTER_COND.generated.h"

UENUM(BlueprintType)
enum class E_SKILL_MASTER_COND : uint8 {
    E_SKILL_MASTER_COND_NONE,
    E_SKILL_MASTER_COND_FAST_ACT,
    E_SKILL_MASTER_COND_WEAK,
    E_SKILL_MASTER_COND_COUNTER,
    E_SKILL_MASTER_COND_CRITICAL,
    E_SKILL_MASTER_COND_ACT_HP_MAX UMETA(Hidden),
    E_SKILL_MASTER_COND_TGT_BST_ANY,
    E_SKILL_MASTER_COND_MULTI_ENEMY,
    E_SKILL_MASTER_COND_BST_HIT,
    E_SKILL_MASTER_COND_INVALID,
};

