#pragma once
#include "CoreMinimal.h"
#include "E_SKILL_LIB_CATEGORY.generated.h"

UENUM(BlueprintType)
enum class E_SKILL_LIB_CATEGORY : uint8 {
    E_SKILL_LIB_CATEGORY_ALL,
    E_SKILL_LIB_CATEGORY_PHISICS,
    E_SKILL_LIB_CATEGORY_FIRE,
    E_SKILL_LIB_CATEGORY_ICE,
    E_SKILL_LIB_CATEGORY_THUNDER,
    E_SKILL_LIB_CATEGORY_WIND,
    E_SKILL_LIB_CATEGORY_LIGHT,
    E_SKILL_LIB_CATEGORY_DARK,
    E_SKILL_LIB_CATEGORY_EVERY,
    E_SKILL_LIB_CATEGORY_RECOVERY,
    E_SKILL_LIB_CATEGORY_AID,
    E_SKILL_LIB_CATEGORY_NODAMAGE_ATK,
    E_SKILL_LIB_CATEGORY_AUTO,
    E_SKILL_LIB_CATEGORY_SPECIAL,
    E_SKILL_LIB_CATEGORY_DOUBLE,
    E_SKILL_LIB_CATEGORY_MAX UMETA(Hidden),
    E_SKILL_LIB_CATEGORY_NONE,
};

