#pragma once
#include "CoreMinimal.h"
#include "E_SKILL_TEKISEI_CATEGORY.generated.h"

UENUM(BlueprintType)
enum class E_SKILL_TEKISEI_CATEGORY : uint8 {
    E_SKILL_TEKISEI_CATEGORY_PHISICS,
    E_SKILL_TEKISEI_CATEGORY_FIRE,
    E_SKILL_TEKISEI_CATEGORY_ICE,
    E_SKILL_TEKISEI_CATEGORY_THUNDER,
    E_SKILL_TEKISEI_CATEGORY_WIND,
    E_SKILL_TEKISEI_CATEGORY_LIGHT,
    E_SKILL_TEKISEI_CATEGORY_DARK,
    E_SKILL_TEKISEI_CATEGORY_ALL,
    E_SKILL_TEKISEI_CATEGORY_NODAMAGE_ATK,
    E_SKILL_TEKISEI_CATEGORY_AID,
    E_SKILL_TEKISEI_CATEGORY_RECOVERY_HP,
    E_SKILL_TEKISEI_CATEGORY_RECOVERY_NA,
    E_SKILL_TEKISEI_CATEGORY_MAX UMETA(Hidden),
    E_SKILL_TEKISEI_CATEGORY_INVALID,
};

