#pragma once
#include "CoreMinimal.h"
#include "E_SKILL_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_SKILL_TYPE : uint8 {
    E_SKILL_TYPE_PHYSICAL_ATK,
    E_SKILL_TYPE_MAGIC_ATK,
    E_SKILL_TYPE_NODAMAGE_ATK,
    E_SKILL_TYPE_RECOVERY,
    E_SKILL_TYPE_AID,
    E_SKILL_TYPE_AUTO_ERUPT_ATTR,
    E_SKILL_TYPE_AUTO_ERUPT,
    E_SKILL_TYPE_SUMMON,
    E_SKILL_TYPE_SPECIAL_ATK,
    E_SKILL_TYPE_CALL,
    E_SKILL_TYPE_NOT_ACT,
    E_SKILL_TYPE_STATUS_UP,
    E_SKILL_TYPE_PHYSICAL_MAGIC_ATK,
    E_SKILL_TYPE_EXTRA_ATK,
    E_SKILL_TYPE_PHYSICAL_RATE_ATK,
    E_SKILL_TYPE_RETURN,
};

