#pragma once
#include "CoreMinimal.h"
#include "E_SKILL_HIT_STAMP_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_SKILL_HIT_STAMP_TYPE : uint8 {
    E_SKILL_HIT_STAMP_TYPE_NONE,
    E_SKILL_HIT_STAMP_TYPE_BLOW,
    E_SKILL_HIT_STAMP_TYPE_SLASH,
    E_SKILL_HIT_STAMP_TYPE_FIRE,
    E_SKILL_HIT_STAMP_TYPE_ICE,
    E_SKILL_HIT_STAMP_TYPE_THUNDER,
    E_SKILL_HIT_STAMP_TYPE_WIND,
    E_SKILL_HIT_STAMP_TYPE_LIGHT,
    E_SKILL_HIT_STAMP_TYPE_DARK,
    E_SKILL_HIT_STAMP_TYPE_ALL,
    E_SKILL_HIT_STAMP_TYPE_TWO,
};

