#pragma once
#include "CoreMinimal.h"
#include "E_SKILL_MASTER_EFT.generated.h"

UENUM(BlueprintType)
enum class E_SKILL_MASTER_EFT : uint8 {
    E_SKILL_MASTER_EFT_CRI_ADD,
    E_SKILL_MASTER_EFT_ATK_ADD,
    E_SKILL_MASTER_EFT_DAMAGE,
    E_SKILL_MASTER_EFT_HIT_100,
    E_SKILL_MASTER_EFT_BST_ADD,
    E_SKILL_MASTER_EFT_BST_UP,
    E_SKILL_MASTER_EFT_MAKA_ADD,
    E_SKILL_MASTER_EFT_TARU_ADD,
    E_SKILL_MASTER_EFT_RAKU_ADD,
    E_SKILL_MASTER_EFT_SUKU_ADD,
    E_SKILL_MASTER_EFT_DRAIN_HP_ADD,
    E_SKILL_MASTER_EFT_DRAIN_MP_ADD,
    E_SKILL_MASTER_EFT_BARRIER_ADD,
};

