#pragma once
#include "CoreMinimal.h"
#include "E_SKILL_BST.generated.h"

UENUM(BlueprintType)
enum class E_SKILL_BST : uint8 {
    E_SKILL_BST_EXCEPT_DEAD,
    E_SKILL_BST_SLEEP_FEAR,
    E_SKILL_BST_ALL,
    E_SKILL_BST_EXCEPT_BOMB_DOWN_DEAD,
    E_SKILL_BST_UROBOROS,
    E_SKILL_BST_EXCEPT_STRAY,
    E_SKILL_BST_BATTLE,
    E_SKILL_BST_ELDJUON,
    E_SKILL_BST_KKIRI,
    E_SKILL_BST_POISON_ILL,
    E_SKILL_BST_JUNAN,
    E_SKILL_BST_AKUEKI,
    E_SKILL_BST_MUSOU,
    E_SKILL_BST_KAMITSUKI,
    E_SKILL_BST_WAZURAI,
    E_SKILL_BST_DLC_ITEM,
};

