#pragma once
#include "CoreMinimal.h"
#include "E_SKILL_INFO_MESS_TIMING.generated.h"

UENUM(BlueprintType)
enum class E_SKILL_INFO_MESS_TIMING : uint8 {
    E_SKILL_INFO_MESS_TIMING_ACTION,
    E_SKILL_INFO_MESS_TIMING_HIT,
    E_SKILL_INFO_MESS_TIMING_AFTER,
    E_SKILL_INFO_MESS_TIMING_PRE_SUMMON,
    E_SKILL_INFO_MESS_TIMING_AFTER_SUMMON,
    E_SKILL_INFO_MESS_TIMING_AFTER_TURN_CHANGE,
    E_SKILL_INFO_MESS_TIMING_AFTER_KUISHIBARI,
    E_SKILL_INFO_MESS_TIMING_CRITICAL_RETURN,
    E_SKILL_INFO_MESS_TIMING_CHARGE_DEAD,
};

