#pragma once
#include "CoreMinimal.h"
#include "E_SKILL_WHISPER_VAL_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_SKILL_WHISPER_VAL_TYPE : uint8 {
    E_SKILL_WHISPER_VAL_TYPE_NONE,
    E_SKILL_WHISPER_VAL_TYPE_DAMAGE_VAL,
    E_SKILL_WHISPER_VAL_TYPE_RECOVERY_VAL,
    E_SKILL_WHISPER_VAL_TYPE_RATE,
    E_SKILL_WHISPER_VAL_TYPE_COST,
    E_SKILL_WHISPER_VAL_TYPE_MINUS_DAM,
    E_SKILL_WHISPER_VAL_TYPE_MINUS_RATE,
    E_SKILL_WHISPER_VAL_TYPE_MINUS_COST,
};

