#pragma once
#include "CoreMinimal.h"
#include "E_SKILL_LIB_STATUS_STEP.generated.h"

UENUM(BlueprintType)
enum class E_SKILL_LIB_STATUS_STEP : uint8 {
    E_SKILL_LIB_STATUS_STEP_NONE,
    E_SKILL_LIB_STATUS_STEP_IN,
    E_SKILL_LIB_STATUS_STEP_CHARA_SEL,
    E_SKILL_LIB_STATUS_STEP_SKILL_GET_CHECK,
    E_SKILL_LIB_STATUS_STEP_SKILL_CHANGE,
    E_SKILL_LIB_STATUS_STEP_SKILL_CHANGE_CHECK,
    E_SKILL_LIB_STATUS_STEP_OUT,
    E_SKILL_LIB_STATUS_STEP_END,
};

