#pragma once
#include "CoreMinimal.h"
#include "E_SKILL_TARGET.generated.h"

UENUM(BlueprintType)
enum class E_SKILL_TARGET : uint8 {
    E_SKILL_TARGET_INV_SIDE_ONE,
    E_SKILL_TARGET_INV_SIDE_ALL,
    E_SKILL_TARGET_SELF_SIDE_ONE,
    E_SKILL_TARGET_SELF_SIDE_ALL,
    E_SKILL_TARGET_SELF,
    E_SKILL_TARGET_ALL_SIDE_ALL,
    E_SKILL_TARGET_INV_SIDE_ALL_RANDOM,
    E_SKILL_TARGET_SELF_SIDE_CMP_ONE,
    E_SKILL_TARGET_SELF_SIDE_CMP_ALL,
    E_SKILL_TARGET_INV_SIDE_STAN_ONE,
    E_SKILL_TARGET_INV_SIDE_STAN_ALL,
};

