#pragma once
#include "CoreMinimal.h"
#include "E_SKILL_LIB_MENU_STEP.generated.h"

UENUM(BlueprintType)
enum class E_SKILL_LIB_MENU_STEP : uint8 {
    E_SKILL_LIB_MENU_STEP_NONE,
    E_SKILL_LIB_MENU_STEP_IN,
    E_SKILL_LIB_MENU_STEP_CATEGORY_SEL,
    E_SKILL_LIB_MENU_STEP_SKILL_SEL,
    E_SKILL_LIB_MENU_STEP_PARTY_SEL,
    E_SKILL_LIB_MENU_STEP_STATUS_VIEW,
    E_SKILL_LIB_MENU_STEP_CHECK_SKILL_GET,
    E_SKILL_LIB_MENU_STEP_SKILL_GET,
    E_SKILL_LIB_MENU_STEP_CHANGE_SKILL_SEL,
    E_SKILL_LIB_MENU_STEP_CHECK_CHANGE_SKILL,
    E_SKILL_LIB_MENU_STEP_SKILL_GET_END,
    E_SKILL_LIB_MENU_STEP_MASTER,
    E_SKILL_LIB_MENU_STEP_MESS_WAIT,
    E_SKILL_LIB_MENU_STEP_ANIM_WAIT,
    E_SKILL_LIB_MENU_STEP_OUT,
    E_SKILL_LIB_MENU_STEP_END,
};

