#pragma once
#include "CoreMinimal.h"
#include "E_SORT_WINDOW_SORT_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_SORT_WINDOW_SORT_TYPE : uint8 {
    CAMP_SKILL,
    CAMP_ITEM_CONSUMPTION,
    CAMP_ITEM_RELIC,
    CAMP_ITEM_VALUABLES,
    CAMP_PARTY_STOCK,
    CAMP_ANALYZE_ENEMY,
    SHOP_ITEM_PURCHASE_CONSUMPTION,
    SHOP_SALE_CONSUMPTION,
    SHOP_SALE_RELIC,
    NOT_USE_00,
    COALESCENCE_RESULT_SELECT_COALESCENCE_RESULT,
    COALESCENCE_COMBINATION_SELECT_COMBINATION,
    COALESCENCE_COMPENDIUM_READ_DEMON,
    AUTOMAP,
    GODPARAMETER_ACQUISITION,
    CAMP_UTSUSEMI,
    SHOP_ITEM_PURCHASE_UTSUSEMI,
    COALESCENCE_RESULT_SELECT_COALESCENCE_RESULT_SP,
    MAX,
};

