#pragma once
#include "CoreMinimal.h"
#include "E_TITLE_TOP_SELECTION.generated.h"

UENUM(BlueprintType)
enum class E_TITLE_TOP_SELECTION : uint8 {
    E_TITLE_TOP_SELECTION_NEWGAME,
    E_TITLE_TOP_SELECTION_LOADGAME,
    E_TITLE_TOP_SELECTION_OPTIONS,
    E_TITLE_TOP_SELECTION_COPYRIGHT,
    E_TITLE_TOP_SELECTION_CONVERT,
    E_TITLE_TOP_SELECTION_END,
    E_TITLE_TOP_SELECTION_TIMEOUT,
};

