#pragma once
#include "CoreMinimal.h"
#include "E_UI_STATUS_SLOT.generated.h"

UENUM(BlueprintType)
enum class E_UI_STATUS_SLOT : uint8 {
    E_UI_STATUS_SLOT_TITLE_BTL_CONDITION,
    E_UI_STATUS_SLOT_TITLE_DROP_ITEMS,
    E_UI_STATUS_SLOT_TITLE_NEW_SKILLS,
    E_UI_STATUS_SLOT_TITLE_INHERITING,
    E_UI_STATUS_SLOT_TITLE_KAMI_SKILLS,
    E_UI_STATUS_SLOT_TITLE_KAMI_SYSTEM,
    E_UI_STATUS_SLOT_TITLE_NEXT_SKILLS,
    E_UI_STATUS_SLOT_TITLE_PARENT_SKILLS,
    E_UI_STATUS_SLOT_TITLE_UNIQUE_SKILLS,
    E_UI_STATUS_SLOT_TITLE_SKILLS,
    E_UI_STATUS_SLOT_EXIT_BUTTON,
    E_UI_STATUS_SLOT_BLANK,
    E_UI_STATUS_SLOT_CURSOR,
    E_UI_STATUS_SLOT_NEW,
    E_UI_STATUS_SLOT_NORMAL,
    E_UI_STATUS_SLOT_NOT,
    E_UI_STATUS_SLOT_SELECT,
    E_UI_STATUS_SLOT_INVISIBLE,
};

