#pragma once
#include "CoreMinimal.h"
#include "E_UI_STATUS_ANIM_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_UI_STATUS_ANIM_TYPE : uint8 {
    E_UI_STATUS_ANIM_TYPE_NONE,
    E_UI_STATUS_ANIM_TYPE_NO_DRAW,
    E_UI_STATUS_ANIM_TYPE_DEVIL_MES_IN,
    E_UI_STATUS_ANIM_TYPE_SKILL_HELP_IN,
    E_UI_STATUS_ANIM_TYPE_NEXT_SKILL_HELP_IN,
    E_UI_STATUS_ANIM_TYPE_LEFT_UI_IN,
    E_UI_STATUS_ANIM_TYPE_RIGHT_UI_IN,
};

