#pragma once
#include "CoreMinimal.h"
#include "E_UI_STATUS_ANIM_TABLE.generated.h"

UENUM(BlueprintType)
enum class E_UI_STATUS_ANIM_TABLE : uint8 {
    E_UI_STATUS_ANIM_TABLE_NO_DRAW,
    E_UI_STATUS_ANIM_TABLE_LEFT_IN,
    E_UI_STATUS_ANIM_TABLE_LEFT_OUT,
    E_UI_STATUS_ANIM_TABLE_RIGHT_IN,
    E_UI_STATUS_ANIM_TABLE_RIGHT_OUT,
    E_UI_STATUS_ANIM_TABLE_SKILL_HELP_IN,
    E_UI_STATUS_ANIM_TABLE_MODEL_SLIDE,
};

