#pragma once
#include "CoreMinimal.h"
#include "E_UI_STATUS_R_ANIM_TABLE.generated.h"

UENUM(BlueprintType)
enum class E_UI_STATUS_R_ANIM_TABLE : uint8 {
    E_UI_STATUS_R_ANIM_TABLE_SKILL_IN,
    E_UI_STATUS_R_ANIM_TABLE_SKILL_IN_WAIT,
    E_UI_STATUS_R_ANIM_TABLE_SKILL_OUT,
    E_UI_STATUS_R_ANIM_TABLE_BLINK,
    E_UI_STATUS_R_ANIM_TABLE_SKILL_OUT_WAIT,
    E_UI_STATUS_R_ANIM_TABLE_SKILL_CURSOR_00,
    E_UI_STATUS_R_ANIM_TABLE_SKILL_CURSOR_01,
};

