#pragma once
#include "CoreMinimal.h"
#include "E_UI_STATUS_UNITE_SOURCE.generated.h"

UENUM(BlueprintType)
enum class E_UI_STATUS_UNITE_SOURCE : uint8 {
    E_UI_STATUS_UNITE_SOURCE_HERO,
    E_UI_STATUS_UNITE_SOURCE_NKM,
    E_UI_STATUS_UNITE_SOURCE_BASE,
    E_UI_STATUS_UNITE_SOURCE_ENEMY,
    E_UI_STATUS_UNITE_SOURCE_BIBLE,
    E_UI_STATUS_UNITE_SOURCE_RESULT,
    E_UI_STATUS_UNITE_SOURCE_UNKNOWN,
};

