#pragma once
#include "CoreMinimal.h"
#include "E_UI_STATUS_OPEN.generated.h"

UENUM(BlueprintType)
enum class E_UI_STATUS_OPEN : uint8 {
    E_UI_STATUS_OPEN_RACE,
    E_UI_STATUS_OPEN_NAME,
    E_UI_STATUS_OPEN_LEVEL,
    E_UI_STATUS_OPEN_EXP,
    E_UI_STATUS_OPEN_HP,
    E_UI_STATUS_OPEN_MP,
    E_UI_STATUS_OPEN_PARAM,
    E_UI_STATUS_OPEN_DEFENCE_AISHOU,
    E_UI_STATUS_OPEN_FACE_ICON,
    E_UI_STATUS_OPEN_CHARA_MODEL,
    E_UI_STATUS_OPEN_SKILL_TEKISEI,
    E_UI_STATUS_OPEN_SKILL,
    E_UI_STATUS_OPEN_PLACE,
    E_UI_STATUS_OPEN_DROP_ITEM,
    E_UI_STATUS_OPEN_TEXT,
    E_UI_STATUS_OPEN_DEFENCE_AISHOU_BAD,
    E_UI_STATUS_OPEN_MP_LIMITED,
    E_UI_STATUS_OPEN_ESSENCE_ICON = 30,
    E_UI_STATUS_IS_UTSUSEMI,
};

