#pragma once
#include "CoreMinimal.h"
#include "E_UI_STATUS_RESISTANCES_BAD_ICON.generated.h"

UENUM(BlueprintType)
enum class E_UI_STATUS_RESISTANCES_BAD_ICON : uint8 {
    E_UI_STATUS_RESISTANCES_BAD_ICON_SLEEP,
    E_UI_STATUS_RESISTANCES_BAD_ICON_DAZZLE,
    E_UI_STATUS_RESISTANCES_BAD_ICON_POISON,
    E_UI_STATUS_RESISTANCES_BAD_ICON_CONFUSE,
    E_UI_STATUS_RESISTANCES_BAD_ICON_CHARM,
    E_UI_STATUS_RESISTANCES_BAD_ICON_CLOSE,
    E_UI_STATUS_RESISTANCES_BAD_ICON_MAX_END,
};

