#pragma once
#include "CoreMinimal.h"
#include "E_UI_STATUS_CTRL_TYPE.generated.h"

UENUM(BlueprintType)
enum class E_UI_STATUS_CTRL_TYPE : uint8 {
    E_UI_STATUS_CTRL_TYPE_BTL_ENEMY,
    E_UI_STATUS_CTRL_TYPE_BTL_PARTY,
    E_UI_STATUS_CTRL_TYPE_BTL_STOCK,
    E_UI_STATUS_CTRL_TYPE_CAMP_PARTY,
    E_UI_STATUS_CTRL_TYPE_CAMP_STOCK,
    E_UI_STATUS_CTRL_TYPE_CAMP_SKILL,
    E_UI_STATUS_CTRL_TYPE_CAMP_ANALYZE,
    E_UI_STATUS_CTRL_TYPE_HEAL_PARTY,
    E_UI_STATUS_CTRL_TYPE_HEAL_STOCK,
    E_UI_STATUS_CTRL_TYPE_UNITE_FIRST,
    E_UI_STATUS_CTRL_TYPE_UNITE_SECOND,
    E_UI_STATUS_CTRL_TYPE_UNITE_SEARCH_FIRST,
    E_UI_STATUS_CTRL_TYPE_UNITE_SEARCH_SECOND,
    E_UI_STATUS_CTRL_TYPE_UNITE_SEARCH_BIBLE_FIRST,
    E_UI_STATUS_CTRL_TYPE_UNITE_SEARCH_BIBLE_SECOND,
    E_UI_STATUS_CTRL_TYPE_UNITE_SPECIAL_FIRST,
    E_UI_STATUS_CTRL_TYPE_UNITE_SPECIAL_SECOND,
    E_UI_STATUS_CTRL_TYPE_BIBLE_LOOK,
    E_UI_STATUS_CTRL_TYPE_BIBLE_LOOK_ALL,
    E_UI_STATUS_CTRL_TYPE_BIBLE_LOOK_ORIGINAL,
    E_UI_STATUS_CTRL_TYPE_BIBLE_NEW,
    E_UI_STATUS_CTRL_TYPE_BIBLE_OLD,
    E_UI_STATUS_CTRL_TYPE_UNITE_USTUSEMI_FIRST,
    E_UI_STATUS_CTRL_TYPE_UNITE_USTUSEMI_SECOND,
    E_UI_STATUS_CTRL_TYPE_UNITE_PARTY,
    E_UI_STATUS_CTRL_TYPE_UNITE_INHERIT_RESULT,
    E_UI_STATUS_CTRL_TYPE_UNITE_SKILL_INHERIT,
    E_UI_STATUS_CTRL_TYPE_UNITE_RESISTANCES_INHERIT_RESULT,
};

