#pragma once
#include "CoreMinimal.h"
#include "E_UNITEPANEL_SORT.generated.h"

UENUM(BlueprintType)
enum class E_UNITEPANEL_SORT : uint8 {
    E_UNITEPANEL_SORT_SORTID,
    E_UNITEPANEL_SORT_ENTRYINDEX,
    E_UNITEPANEL_SORT_LEVEL,
    E_UNITEPANEL_SORT_HP,
    E_UNITEPANEL_SORT_MP,
    E_UNITEPANEL_SORT_DEVILGROUP,
    E_UNITEPANEL_SORT_COST,
    E_UNITEPANEL_SORT_BOOKENTRY,
    E_UNITEPANEL_SORT_ABLEFUSION,
    E_UNITEPANEL_SORT_NEWDISP,
    E_UNITEPANEL_SORT_UTSUSEMINEWDISP,
    E_UNITEPANEL_SORT_NAME,
    E_UNITEPANEL_SORT_DEF_PHISICS,
    E_UNITEPANEL_SORT_DEF_FIRE,
    E_UNITEPANEL_SORT_DEF_ICE,
    E_UNITEPANEL_SORT_DEF_THUNDER,
    E_UNITEPANEL_SORT_DEF_WIND,
    E_UNITEPANEL_SORT_DEF_LIGHT,
    E_UNITEPANEL_SORT_DEF_DARK,
    E_UNITEPANEL_SORT_AVAILABLEBUY,
    E_UNITEPANEL_SORT_DEVILGROUP01,
    E_UNITEPANEL_SORT_DEVILGROUP02,
    E_UNITEPANEL_SORT_LEVEL01,
    E_UNITEPANEL_SORT_LEVEL02,
    E_UNITEPANEL_SORT_NAME01,
    E_UNITEPANEL_SORT_NAME02,
    E_UNITEPANEL_SORT_POSSESSION,
};

