#pragma once
#include "CoreMinimal.h"
#include "E_UNITECHARAPANEL_BTNHELPTYPE.generated.h"

UENUM(BlueprintType)
enum class E_UNITECHARAPANEL_BTNHELPTYPE : uint8 {
    E_UNITEPANEL_BTNHELP_DUMMY,
    E_UNITEPANEL_BTNHELP_PARTY_SRC,
    E_UNITEPANEL_BTNHELP_PARTY_DST,
    E_UNITEPANEL_BTNHELP_FUSION_1,
    E_UNITEPANEL_BTNHELP_FUSION_2,
    E_UNITEPANEL_BTNHELP_SEARCH,
    E_UNITEPANEL_BTNHELP_SPECIAL_1,
    E_UNITEPANEL_BTNHELP_SPECIAL_2,
    E_UNITEPANEL_BTNHELP_UTSUSEMI_1,
    E_UNITEPANEL_BTNHELP_UTSUSEMI_2,
    E_UNITEPANEL_BTNHELP_UTSUSEMI_SKILL,
    E_UNITEPANEL_BTNHELP_DEVILBOOK_1,
    E_UNITEPANEL_BTNHELP_DEVILBOOK_2,
};

