#pragma once
#include "CoreMinimal.h"
#include "E_UNITECHARAPANEL_MENUTYPE.generated.h"

UENUM(BlueprintType)
enum class E_UNITECHARAPANEL_MENUTYPE : uint8 {
    E_UNITECHARAPANEL_MENU_PARTY,
    E_UNITECHARAPANEL_MENU_DEVILBOOK,
    E_UNITECHARAPANEL_MENU_UTSUSEMI,
    E_UNITECHARAPANEL_MENU_FUSION_COMBINE,
    E_UNITECHARAPANEL_MENU_FUSION_SEARCH,
    E_UNITECHARAPANEL_MENU_SPECIAL,
    E_UNITECHARAPANEL_MENU_SPECIAL_COMBINE,
};

