#pragma once
#include "CoreMinimal.h"
#include "E_UNITECHARAPANEL_ERRORTYPE.generated.h"

UENUM(BlueprintType)
enum class E_UNITECHARAPANEL_ERRORTYPE : uint8 {
    E_UNITEPANEL_ERROR_NONE,
    E_UNITEPANEL_ERROR_HAVE,
    E_UNITEPANEL_ERROR_CANNOT,
    E_UNITEPANEL_ERROR_LEVEL,
    E_UNITEPANEL_ERROR_SOZAI,
    E_UNITEPANEL_ERROR_MONEY,
    E_UNITEPANEL_ERROR_STOCK,
    E_UNITEPANEL_ERROR_ENTRY,
    E_UNITEPANEL_ERROR_SCENARIO,
};

