#pragma once
#include "CoreMinimal.h"
#include "E_WIDGET_PRIO.generated.h"

UENUM(BlueprintType)
enum class E_WIDGET_PRIO : uint8 {
    E_WIDGET_PRIO_DEFAULT,
    E_WIDGET_PRIO_BACK_FADE,
    E_WIDGET_PRIO_RYUKETSU,
    E_WIDGET_PRIO_MAP,
    E_WIDGET_PRIO_MAP_MAGATSUHI,
    E_WIDGET_PRIO_MAP_AACTION_WINDOW,
    E_WIDGET_PRIO_MAP_INFO,
    E_WIDGET_PRIO_RYUKETSU_FT_LIST,
    E_WIDGET_PRIO_CAMP,
    E_WIDGET_PRIO_CAMP_HELPMESSAGE,
    E_WIDGET_PRIO_BATTLE,
    E_WIDGET_PRIO_BATTLE_CHARAPANEL,
    E_WIDGET_PRIO_BATTLE_MESSAGE_WINDOW,
    E_WIDGET_PRIO_MESSAGE_WIN,
    E_WIDGET_PRIO_DIALOG_WINDOW,
    E_WIDGET_PRIO_BACK_LOG,
    E_WIDGET_PRIO_SORT_WINDOW,
    E_WIDGET_PRIO_RYUKETSU_FRONT1,
    E_WIDGET_PRIO_RYUKETSU_FRONT2,
    E_WIDGET_PRIO_BUTTON_HELP,
    E_WIDGET_PRIO_CAMP_DIALOG_WINDOW,
    E_WIDGET_PRIO_HEAL_RECOVERY_ALL,
    E_WIDGET_PRIO_MAP_FRONT,
    E_WIDGET_PRIO_RYUKETSU_DIALOG_WINDOW,
    E_WIDGET_PRIO_BATTLE_DIALOG_WINDOW,
    E_WIDGTE_PRIO_SCREEN_FADE,
    E_WIDGET_PRIO_BATTLE_TURNCHANGE,
    E_WIDGET_PRIO_LOADING,
    E_WIDGET_PRIO_DEBUG_MENU,
    E_WIDGET_PRIO_DEBUG_MENU_FUNC,
    E_WIDGET_PRIO_MAX UMETA(Hidden),
};

